### ISSUE TITLE
navbar doesn't change when logged in user goes to the log in page

### ISSUE THREAD

**Issue by lingxz** [lingxz/todoapp#17]
Before the user logs in, the navbar is the before logged in navbar (with the register/login buttons). 
After the user logs in, the navbar changes to the logged in navbar (with the logout buttons etc)
but if the user logs in and clicks on "back", user is brought back to login page but navbar is still the logged in navbar.

**Comment by astraldawn** [comment]
Backspace is not a logout. What should happen is when a user is logged in, attempting to go to the login page should redirect to main screen.
